name: Run Tests with Pytest

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # runs daily at 03:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest and generate HTML report
      run: |
        pytest .

    - name: Upload report as artifact
      if: always()  # ensures this runs even if previous steps failed
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html
